CREATE FUNCTION FN_SYS_FORMATA_DATA(@DATA DATETIME, @CODIGO_CONVERSAO INT)
	RETURNS VARCHAR(30)
BEGIN
	DECLARE @DATA_FORMATADA VARCHAR(30) 

	SET @DATA_FORMATADA = REPLACE(CONVERT(VARCHAR, ISNULL(@DATA, ''), @CODIGO_CONVERSAO), '01/01/1900', '')

	RETURN @DATA_FORMATADA 
	
END