CREATE FUNCTION FN_VERIFICA_SE_CPF_E_VALIDO(@CPF CHAR(11))

	RETURNS VARCHAR(5)
	AS

BEGIN	

	DECLARE @CONT INT = 2
	DECLARE @NUMERO1 INT, @NUMERO2 INT, @NUMERO3 INT, @NUMERO4 INT, @NUMERO5 INT, @NUMERO6 INT, @NUMERO7 INT, @NUMERO8 INT, @NUMERO9 INT, @NUMERO10 INT, @NUMERO11 INT 
	DECLARE @PRIMEIRA_VALIDACAO INT
	DECLARE @SEGUNDA_VALIDACAO INT
	
	
	SELECT @NUMERO1 = CAST(LEFT(@CPF, 1) AS INT)
	SET @NUMERO2 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 2), 1) AS INT)
	SET @NUMERO3 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 3), 1) AS INT)
	SET @NUMERO4 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 4), 1) AS INT)
	SET @NUMERO5 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 5), 1) AS INT)
	SET @NUMERO6 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 6), 1) AS INT)
	SET @NUMERO7 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 7), 1) AS INT)
	SET @NUMERO8 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 8), 1) AS INT)
	SET @NUMERO9 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 9), 1) AS INT)
	SET @NUMERO10 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 10), 1) AS INT)
	SET @NUMERO11 = CAST(RIGHT(LEFT(CAST(@CPF AS VARCHAR), 11), 1) AS INT)
	
	
	SET @PRIMEIRA_VALIDACAO = (@NUMERO1 * 10 + @NUMERO2 * 9 + @NUMERO3 * 8 + @NUMERO4 * 7 + @NUMERO5 * 6 + @NUMERO6 * 5 + @NUMERO7 * 4 + @NUMERO8 * 3 + @NUMERO9 * 2) * 10 % 11
	SET @SEGUNDA_VALIDACAO = (@NUMERO1 * 11 + @NUMERO2 * 10 + @NUMERO3 * 9 + @NUMERO4 * 8 + @NUMERO5 * 7 + @NUMERO6 * 6 + @NUMERO7 * 5 + @NUMERO8 * 4 + @NUMERO9 * 3 + @NUMERO10 * 2) * 10 % 11
	
	
	IF @NUMERO10 = @PRIMEIRA_VALIDACAO AND @NUMERO11 = @SEGUNDA_VALIDACAO BEGIN
	
		RETURN 'TRUE'
	
	END
		
	RETURN 'FALSE'
		

END

